name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: xcodebuild -project 'MyBP.xcodeproj' -scheme 'MyBP' -destination 'platform=iOS Simulator,name=iPhone 14' test
    - name: Build App
      run: xcodebuild -project 'MyBP.xcodeproj' -scheme 'MyBP' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
